version: 3
jobs:
  build:
    docker:
      - image: cimg/php:8.0.20
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run:
          name: php test
          command: php artisan test
